const photographer = {
  name: "Aria",
  tagline: "Photographer Tagline",
};

const portfolioCategories = [
  "all",
  "portraits",
  "nature",
  "travel",
  "events",
  "weddings",
];

const portfolioPhotos = [
  {
    id: 1,
    title: "Title Placeholder",
    category: "portraits",
    image: "portraits/portrait4.jpg",
    description: "description placeholder",
    date: "date placeholder",
  },
  {
    id: 2,
    title: "Title Placeholder",
    category: "events",
    image: "events/event7.jpg",
    description: "description placeholder",
    date: "date placeholder",
  },

  {
    id: 3,
    title: "Title Placeholder",
    category: "portraits",
    image: "portraits/portrait1.jpg",
    description: "description placeholder",
    date: "date placeholder",
  },
  {
    id: 4,
    title: "Title Placeholder",
    category: "travel",
    image: "travel/travel1.jpg",
    description: "description placeholder",
    date: "date placeholder",
  },
  {
    id: 5,
    title: "Title Placeholder",
    category: "weddings",
    image: "weddings/wedding1.jpg",
    description: "description placeholder",
    date: "date placeholder",
  },

  {
    id: 6,
    title: "Title Placeholder",
    category: "events",
    image: "events/event2.jpg",
    description: "description placeholder",
    date: "date placeholder",
  },
  {
    id: 7,
    title: "Title Placeholder",
    category: "nature",
    image: "nature/nature2.jpg",
    description: "description placeholder",
    date: "date placeholder",
  },
  {
    id: 8,
    title: "Title Placeholder",
    category: "portraits",
    image: "portraits/portrait2.jpg",
    description: "description placeholder",
    date: "date placeholder",
  },
  {
    id: 9,
    title: "Title Placeholder",
    category: "travel",
    image: "travel/travel2.jpg",
    description: "description placeholder",
    date: "date placeholder",
  },
  {
    id: 10,
    title: "Title Placeholder",
    category: "weddings",
    image: "weddings/wedding2.jpg",
    description: "description placeholder",
    date: "date placeholder",
  },
  {
    id: 11,
    title: "Title Placeholder",
    category: "events",
    image: "events/event3.jpg",
    description: "description placeholder",
    date: "date placeholder",
  },
  {
    id: 12,
    title: "Title Placeholder",
    category: "events",
    image: "events/event1.jpg",
    description: "description placeholder",
    date: "date placeholder",
  },
  {
    id: 13,
    title: "Title Placeholder",
    category: "portraits",
    image: "portraits/portrait3.jpg",
    description: "description placeholder",
    date: "date placeholder",
  },
  {
    id: 14,
    title: "Title Placeholder",
    category: "travel",
    image: "travel/travel3.jpg",
    description: "description placeholder",
    date: "date placeholder",
  },
  {
    id: 15,
    title: "Title Placeholder",
    category: "weddings",
    image: "weddings/wedding3.jpg",
    description: "description placeholder",
    date: "date placeholder",
  },
  {
    id: 16,
    title: "Title Placeholder",
    category: "events",
    image: "events/event4.jpg",
    description: "description placeholder",
    date: "date placeholder",
  },
  {
    id: 17,
    title: "Title Placeholder",
    category: "nature",
    image: "nature/nature7.jpg",
    description: "description placeholder",
    date: "date placeholder",
  },
  {
    id: 18,
    title: "Title Placeholder",
    category: "nature",
    image: "nature/nature1.jpg",
    description: "description placeholder",
    date: "date placeholder",
  },
  {
    id: 19,
    title: "Title Placeholder",
    category: "travel",
    image: "travel/travel4.jpg",
    description: "description placeholder",
    date: "date placeholder",
  },
  {
    id: 20,
    title: "Title Placeholder",
    category: "weddings",
    image: "weddings/wedding4.jpg",
    description: "description placeholder",
    date: "date placeholder",
  },

  {
    id: 21,
    title: "Title Placeholder",
    category: "events",
    image: "events/event5.jpg",
    description: "description placeholder",
    date: "date placeholder",
  },
  {
    id: 22,
    title: "Title Placeholder",
    category: "nature",
    image: "nature/nature5.jpg",
    description: "description placeholder",
    date: "date placeholder",
  },
  {
    id: 21,
    title: "Title Placeholder",
    category: "travel",
    image: "travel/travel6.jpg",
    description: "description placeholder",
    date: "date placeholder",
  },
  {
    id: 24,
    title: "Title Placeholder",
    category: "travel",
    image: "travel/travel5.jpg",
    description: "description placeholder",
    date: "date placeholder",
  },
  {
    id: 25,
    title: "Title Placeholder",
    category: "weddings",
    image: "weddings/wedding5.jpg",
    description: "description placeholder",
    date: "date placeholder",
  },
  {
    id: 26,
    title: "Title Placeholder",
    category: "events",
    image: "events/event6.jpg",
    description: "description placeholder",
    date: "date placeholder",
  },
  {
    id: 27,
    title: "Title Placeholder",
    category: "nature",
    image: "nature/nature6.jpg",
    description: "description placeholder",
    date: "date placeholder",
  },
  {
    id: 28,
    title: "Title Placeholder",
    category: "portraits",
    image: "portraits/portrait6.jpg",
    description: "description placeholder",
    date: "date placeholder",
  },
  {
    id: 29,
    title: "Title Placeholder",
    category: "nature",
    image: "nature/nature3.jpg",
    description: "description placeholder",
    date: "date placeholder",
  },
  {
    id: 30,
    title: "Title Placeholder",
    category: "weddings",
    image: "weddings/wedding6.jpg",
    description: "description placeholder",
    date: "date placeholder",
  },
  {
    id: 31,
    title: "Title Placeholder",
    category: "portraits",
    image: "portraits/portrait5.jpg",
    description: "description placeholder",
    date: "date placeholder",
  },
  {
    id: 32,
    title: "Title Placeholder",
    category: "nature",
    image: "nature/nature4.jpg",
    description: "description placeholder",
    date: "date placeholder",
  },
  {
    id: 33,
    title: "Title Placeholder",
    category: "travel",
    image: "travel/travel9.jpg",
    description: "description placeholder",
    date: "date placeholder",
  },
  {
    id: 34,
    title: "Title Placeholder",
    category: "travel",
    image: "travel/travel7.jpg",
    description: "description placeholder",
    date: "date placeholder",
  },
  {
    id: 35,
    title: "Title Placeholder",
    category: "weddings",
    image: "weddings/wedding7.jpg",
    description: "description placeholder",
    date: "date placeholder",
  },
  {
    id: 36,
    title: "Title Placeholder",
    category: "events",
    image: "events/event8.jpg",
    description: "description placeholder",
    date: "date placeholder",
  },
  {
    id: 37,
    title: "Title Placeholder",
    category: "nature",
    image: "nature/nature8.jpg",
    description: "description placeholder",
    date: "date placeholder",
  },
  {
    id: 38,
    title: "Title Placeholder",
    category: "nature",
    image: "nature/nature10.jpg",
    description: "description placeholder",
    date: "date placeholder",
  },
  {
    id: 39,
    title: "Title Placeholder",
    category: "travel",
    image: "travel/travel8.jpg",
    description: "description placeholder",
    date: "date placeholder",
  },
  {
    id: 40,
    title: "Title Placeholder",
    category: "weddings",
    image: "weddings/wedding8.jpg",
    description: "description placeholder",
    date: "date placeholder",
  },

  {
    id: 41,
    title: "Title Placeholder",
    category: "nature",
    image: "nature/nature9.jpg",
    description: "description placeholder",
    date: "date placeholder",
  },
  {
    id: 42,
    title: "Title Placeholder",
    category: "travel",
    image: "travel/travel10.jpg",
    description: "description placeholder",
    date: "date placeholder",
  },
];
